# Generated by Django 4.2.3 on 2023-07-28 00:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skysend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsettings',
            name='mailing_client',
        ),
        migrations.RemoveField(
            model_name='mailingsettings',
            name='mailing_message',
        ),
        migrations.AddField(
            model_name='mailingclient',
            name='mailing_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skysend.mailingsettings'),
        ),
        migrations.AddField(
            model_name='mailingmessage',
            name='mailing_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skysend.mailingsettings'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='sending_time',
            field=models.TimeField(default=datetime.datetime(2023, 7, 28, 3, 37, 25, 505537), verbose_name='время рассылки'),
        ),
    ]
