# Generated by Django 4.2.3 on 2023-07-28 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skysend', '0002_remove_mailingsettings_mailing_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='sending_time',
            field=models.TimeField(default=datetime.datetime(2023, 7, 28, 23, 45, 10, 517126), verbose_name='время рассылки'),
        ),
    ]
