# Generated by Django 4.2.3 on 2023-07-28 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skysend', '0003_alter_mailingsettings_sending_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Вкл/Выкл рассылку'),
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='mailing_date_next',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время следующей отправки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='sending_time',
            field=models.TimeField(default=datetime.datetime(2023, 7, 29, 2, 25, 30, 827462), verbose_name='время рассылки'),
        ),
    ]
