# Generated by Django 4.2.3 on 2023-07-29 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skysend', '0005_mailingsettings_begin_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailingsettings',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='begin_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 16, 2, 40, 388443), verbose_name='Начала рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='sending_time',
            field=models.TimeField(default=datetime.datetime(2023, 7, 29, 16, 2, 40, 388408), verbose_name='время рассылки'),
        ),
    ]
