# Generated by Django 4.2.3 on 2023-07-30 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skysend', '0006_rename_create_date_mailingsettings_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'ordering': ['id'], 'verbose_name': 'Настройка рассылка', 'verbose_name_plural': 'Настройки рассылки'},
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='begin_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 31, 1, 7, 41, 377893), verbose_name='Начала рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='sending_time',
            field=models.TimeField(default=datetime.datetime(2023, 7, 31, 1, 7, 41, 377830), verbose_name='время рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='status_mailing',
            field=models.CharField(choices=[('created', 'Создана'), ('edited', 'Изменено'), ('running', 'Запущена'), ('completed', 'Завершена')], verbose_name='статус рассылки'),
        ),
    ]
