# Generated by Django 4.2.3 on 2023-07-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skychimp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailingMessage',
        ),
        migrations.DeleteModel(
            name='MailingSettings',
        ),
        migrations.DeleteModel(
            name='MailingStatus',
        ),
    ]
